name: No Response

# When a comment is created and every day at 08:05
on:
   issue_comment:
      types: [created]
   schedule:
      - cron: '5 8 * * *'

jobs:
   noResponse:
      runs-on: ubuntu-latest
      steps:
         - uses: lee-dohm/no-response@v0.5.0
           with:
              token: ${{ github.token }}
              daysUntilClose: 21
              responseRequiredLabel: more-info-needed
              closeComment: >
                 This issue has been automatically closed due to a lack of response.
                 If your problem persists please open a new issue including any additional detail
                 requested from this issue.
                 For more detail on the issues/pull requests see [ISSUES_AND_PULL_REQUESTS](https://github.com/steveukx/git-js/blob/main/docs/ISSUES_AND_PULL_REQUESTS.md)
